# Project Information
site_name: TOSTADAS
site_author: SciComp
site_description: >-
  Tostadas
# Repository
repo_name: CDCgov/tostadas
repo_url: https://github.com/CDCgov/tostadas/
edit_uri: https://github.com/CDCgov/tostadas/edit/main/docs/

# Copyright
copyright: Public Domain - CDC

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true


# Customization
extra:
  social:
    - icon: fontawesome/solid/users
      link: https://www.cdc.gov/amd/index.html
    - icon: fontawesome/brands/github
      link: https://github.com/CDCgov
  version:
    provider: mike


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.md_in_html
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: CDCgov
      repo: tostadas
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - Overview: index.md
  - Getting Started:
    - Installation: user-guide/installation.md
    - NCBI Account Setup: user-guide/general_NCBI_submission_guide.md
  - User Guide:
    - Submission Guide: user-guide/submission_guide.md
    - Measles Submission: user-guide/measles_guide.md
    - Wastewater Submission: user-guide/wastewater_guide.md
    - PulseNet Submission: user-guide/pulsenet_guide.md
    - CDC User Guide: user-guide/cdc-user-guide.md
  - Annotation:
    - Custom Metadata: user-guide/custom_metadata_guide.md
    - User Provided Annotation: user-guide/user_provided_annotation_guide.md
    - VADR Installation: user-guide/vadr_install.md
  - Reference:
    - Parameters: user-guide/parameters.md
    - Output: user-guide/outputs.md
    - Glossary: user-guide/glossary.md
  - Developer Guide:
    - Developer Notes: developer_notes.md
  - Support:
    - Troubleshooting: user-guide/troubleshooting.md
    - Get in Touch: user-guide/get-in-touch.md
    - Contributions: user-guide/contributions.md
