---
NCBI_username:
NCBI_password:
NCBI_ftp_host: 'ftp-private.ncbi.nlm.nih.gov'
NCBI_sftp_host: 'sftp-private.ncbi.nlm.nih.gov'
NCBI_API_URL: 'https://submit.ncbi.nlm.nih.gov/api/2.0/files/FILE_ID/?format=attachment'
table2asn_email: '' # To submit to GenBank, use 'gb-admin@ncbi.nlm.nih.gov'
BioSample_package: "SARS-CoV-2.wwsurv.1.0" # see assets/biosample_fields_key.yaml for supported BioSample pkgs
Role: owner
Type: institute
NCBI_Namespace:
Org_ID: 
Submitting_Org: CDC
Submitting_Org_Dept: 
Street: 1600 Clifton Rd
City: Atlanta
State: GA
Postal_code: 30329
Country: USA
Email: test@cdc.gov
Phone: ""
Specified_Release_Date: ""
Submitter:
  '@email': test9@cdc.gov
  '@alt_email': test@cdc.gov
  Name:
    First: John
    Last: Doe
